# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
#

# Rough draft for postgres dev container.
# Not for prod use!

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
      target: final
    environment:
      # process arg for runtime checks, but not used for building as that is cached already
      - DATABASE_URL=postgres://postgres:123@database:5432
      # tells application to ignore missing keys (s3, openai, etc...)
      - DEV_ENV=true
      - RUST_LOG=info
      - REQ_DELAY_MS=100
    depends_on:
      database:
        condition: service_healthy
        # if database restarts, restart the scraper
        restart: true
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    user: postgres
    # if move to prod, pull from a secrets file
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

